### ISSUE TITLE
Some commands simply weren't executed in automation

### ISSUE THREAD

**Issue by Pirol62** [deiger/AirCon#110]
Hi, as everything worked fluently for days now, yesterday the climate have been started via automation successfully.
All other automations, modifying fanspeed and temperature during the evening did not run even the automation triggered correctly.

I.e. the automation which sets the quiet mode at 23:50.

![image](https://user-images.githubusercontent.com/48820003/120920704-6aa2b280-c6c0-11eb-9092-98e93e42c0b6.png)
The switch does the following:
````
- platform: mqtt
  name: "Klima Ruhemodus"
  command_topic: "hisense_ac/ca2c4fa285af/t_fan_mute/command"
  state_topic: "hisense_ac/ca2c4fa285af/t_fan_mute/status"
  payload_on: "on"
  payload_off: "off"
  qos: 1
````
The second command did not work as well:
![image](https://user-images.githubusercontent.com/48820003/120920745-a50c4f80-c6c0-11eb-8b01-1046a33a3bf8.png)
but the last one, not related to climate worked:
![image](https://user-images.githubusercontent.com/48820003/120920764-bd7c6a00-c6c0-11eb-8340-90ab9086e94f.png)

Another automation which should have runned before and reduced the fan speed did not work either.
During that time, the climate entity wasn't updated.
A restart of the hisense addon did not change anything so the automation this morning which should switch off the a/c did not work either

This morning I switched off the a/c via hisense app.

10 minutes ago, I switched the a/c on and off via lovelace. That worked

Can it be, that the Hisense app and the HA addon disturbes each other? As my automations are quite new I still check the working mode of the a/c in the official Hisense app. I additionally noticed, that the app had to be stopped hard and restarted, before it shows the right status. Can it be, that the app avoids the a/c to receive commands from other sources, when the hisense app is still avtive in mobiles background?

As I do not have logs in HA, I have no other idea to find the issue.

For information the automation which starts the a/c:
````
choose:
  - conditions:
      - condition: template
        value_template: '{{ now().hour in(19,20) }}'
    sequence:
      - service: climate.set_temperature
        target:
          entity_id: climate.klima_schlafzimmer
        data:
          temperature: '16'
          hvac_mode: cool
      - service: climate.set_fan_mode
        target:
          entity_id: climate.klima_schlafzimmer
        data:
          fan_mode: higher
      - delay: '02:00:00'
      - service: climate.set_temperature
        target:
          entity_id: climate.klima_schlafzimmer
        data:
          temperature: '19'
          hvac_mode: cool
      - service: climate.set_fan_mode
        target:
          entity_id: climate.klima_schlafzimmer
        data:
          fan_mode: medium
default:
  - service: climate.set_temperature
    target:
      entity_id: climate.klima_schlafzimmer
    data:
      temperature: '{{ states(''input_number.cooling_temperature'')|int}}'
      hvac_mode: cool
````
The part after the delay haven't been executed.
