### ISSUE TITLE
HA reverts the temperature right after having it set

### ISSUE THREAD

**Issue by Pirol62** [deiger/AirCon#124]
Hi, I have the following sequence in a script which is executed by an automation:
````
        - service: climate.set_temperature
          target:
            entity_id: climate.klima_schlafzimmer
          data:
            temperature: "16"
            hvac_mode: cool
        - delay:
            seconds: 10
        - service: climate.set_fan_mode
          target:
            entity_id: climate.klima_schlafzimmer
          data:
            fan_mode: "{{fan_mode}}"
````
The sequence worked two or three days perfect but since two days the temperature switches back to the one which was active before the script starts
![image](https://user-images.githubusercontent.com/48820003/127106175-402f98da-e408-405d-a3fa-1065163fcf03.png)
At 19:15 the target temp is set to 16 and directly back to 19.
A little later I set the target temp via lovelace.

What happens here? Has anybody a tip?

The a/c is a Hisense.

**Comment by LazyEngineerToBe** [comment]
I have a similar issue. When I set the AC to Cooling mode it sets the temperature to 26C. I then have to manually set it to 20 C. If I turn off the AC and set it to cool again it reverts back to 26 C. It's an Hisense brand AC.

![image](https://user-images.githubusercontent.com/17530304/130142540-51e0f080-53f6-491e-bd28-5c745f498373.png)

**Comment by Pirol62** [comment]
Hi, I thinkj, it a hisense problem and c annot be solved by the addon.
That's how I solved my issue:
````
command_boost_air_condition:
  alias: Boost Klimaanlage
  mode: single
  sequence:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ states('climate.klima_schlafzimmer') != 'off' }}"
          sequence:
            - service: script.turn_on
              entity_id: script.add_log
              data:
                variables:
                  name: "Climate boost startet. A/C was active. Fan mode {{fan_mode }}"
                  message: "{{states('sensor.wt_schlafzimmer_temperature')}} Grad."
            - service: switch.turn_off
              entity_id: switch.klima_ruhemodus
            - service: input_boolean.turn_on
              entity_id: input_boolean.air_condition_boost
            - service: climate.set_temperature
              target:
                entity_id: climate.klima_schlafzimmer
              data:
                temperature: "16"
            - delay:
                seconds: 2
            - service: climate.set_fan_mode
              target:
                entity_id: climate.klima_schlafzimmer
              data:
                fan_mode: "{{fan_mode}}"
      default:
        - service: script.turn_on
          entity_id: script.add_log
          data:
            variables:
              name: "Climate boost startet. Fan mode {{fan_mode }}"
              message: "{{states('sensor.wt_schlafzimmer_temperature')}} Grad."
        - service: input_boolean.turn_on
          entity_id: input_boolean.air_condition_boost
        - service: climate.set_temperature
          target:
            entity_id: climate.klima_schlafzimmer
          data:
            temperature: "16"
            hvac_mode: cool
        - delay:
            seconds: 10
        - service: climate.set_fan_mode
          target:
            entity_id: climate.klima_schlafzimmer
          data:
            fan_mode: "{{fan_mode}}"
        - delay:
            minutes: 1
        - service: climate.set_temperature
          target:
            entity_id: climate.klima_schlafzimmer
          data:
            temperature: "16"
    - alias: "wait till Temperature below 19,3"
      wait_template: "{{ states('sensor.wt_schlafzimmer_temperature') |float < 19.3 }}"
    - service: climate.set_temperature
      target:
        entity_id: climate.klima_schlafzimmer
      data:
        temperature: "{{ states('input_number.cooling_temperature')|int}}"
    - service: climate.set_fan_mode
      target:
        entity_id: climate.klima_schlafzimmer
      data:
        fan_mode: medium
    - service: input_boolean.turn_off
      entity_id: input_boolean.air_condition_boost
    - condition: time
      after: "23:50:00"
      before: "06:30:00"
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.outside_temperature
              below: 13
          sequence:
            - service: climate.set_hvac_mode
              target:
                entity_id: climate.klima_schlafzimmer
              data:
                hvac_mode: "off"
      default:
        - service: switch.turn_on
          entity_id: switch.klima_ruhemodus
````
