### ISSUE TITLE
"Missing option 'app' in root in HiSense Air Conditioners" configuration error

### ISSUE THREAD

**Issue by nikogusm** [deiger/AirCon#125]
Hi, every time I try to setup deiger/AirCon I get this error when saving the configuration:

> Impossibile salvare la configurazione del componente aggiuntivo, Missing option 'app' in root in HiSense Air Conditioners (c34eddb3_hisense_ac). Got {'log_level': 'INFO', 'mqtt_host': 'core-mosquitto', 'mqtt_user': '******', 'mqtt_pass': '******', 'port': 8883}

I tried also with port 1883 but it's not working. What I'm missing?

Thanks

**Comment by Mika56** [comment]
Hi,
Here's a working configuration:
```yaml
log_level: INFO
mqtt_host: 127.0.0.1
mqtt_user: mqttf
mqtt_pass: mqtt
port: 8888
app:
  - username: me@somewehere.com
  - password: password
  - code: fglair-eu
```
`code` values are presented in the repository's main readme
