### ISSUE TITLE
Error compose docker

### ISSUE THREAD

**Issue by psaidac** [deiger/AirCon#140]
hi all,
here is my docker_compose.yaml:
version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
    - /home/pi/homeassistant:/config
    environment:
    - TZ=Europe/Rome
    network_mode: host
    restart: always
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/home/pi/mosquitto/config:/mosquitto/config"
    - "/home/pi/mosquitto/log:/mosquitto/log"
    - "/home/pi/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883"
  copy_config:
    build:
    context: .
    command: >
    sh -c "cp -n ./config/options.json /config/"
    volumes:
    - /home/pi/hisense/config:/config
  hisense_ac:
    depends_on:
    - copy_config
    image: deiger/aircon:0.3.9
    container_name: hisense_ac
    healthcheck:
    disable: true
    environment:
    - CONFIG_DIR=/config
    - OPTIONS_FILE=/config/options.json
    network_mode: host
    volumes:
    - /home/pi/hisense/config:/config

I'd create a folder named hisense/config in home/pi, in the config i put the options.json.
When i send this command:  docker-compose up -d
i receive this error:
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yaml", line 26, column 5
could not find expected ':'
  in "./docker-compose.yaml", line 27, column 5
can you help me please?

**Comment by Lx** [comment]
Your YAML file needs to be properly indented.  It probably is, but the indentation doesn't show in your message.  You can keep indentation in GitHub messages by putting ` ```yaml ` above and ` ``` ` below, like this:

    ```yaml
    version: '3'
    # ...
    ```

I think your original YAML looked like this:

```yaml
version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/pi/homeassistant:/config
    environment:
      - TZ=Europe/Rome
    network_mode: host
    restart: always
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "/home/pi/mosquitto/config:/mosquitto/config"
      - "/home/pi/mosquitto/log:/mosquitto/log"
      - "/home/pi/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
      - "1883:1883"
  copy_config:
    build:
      context: .
    command: >
      sh -c "cp -n ./config/options.json /config/"
    volumes:
      - /home/pi/hisense/config:/config
  hisense_ac:
    depends_on:
      - copy_config
    image: deiger/aircon:0.3.9
    container_name: hisense_ac
    healthcheck:
      disable: true
    environment:
      - CONFIG_DIR=/config
      - OPTIONS_FILE=/config/options.json
    network_mode: host
    volumes:
      - /home/pi/hisense/config:/config
```

If so, I can't see any obvious problem with the YAML to cause that error.
