### ISSUE TITLE
401 Unauthorized error when trying to start docker container

### ISSUE THREAD

**Issue by RebelElephant** [deiger/AirCon#156]
Hi,

I am getting the following error when trying to start the docker container:
```
E0424 07:12:40.865  discovery.py:43] Failed to login to Hisense server:
Status 401: 'Unauthorized'
```
My docker-compose is as follows:
```
version: '3'
services:
  hisense_ac:
    image: deiger/aircon:0.3.10
    container_name: hisenseac
    healthcheck:
      disable: true
    environment:
      - CONFIG_DIR=/config
      - OPTIONS_FILE=/config/options.json
    volumes:
      - /home/docker/hisense:/config
```

and the options.json file in the /config directory is as follows:
```
{
  "app": [
    {
      "username": "<<redacted>>",
      "password": "<<redacted>>",
      "code": "fglair-eu"
    }
  ],
  "log_level": "DEBUG",
  "mqtt_host": "localhost",
  "mqtt_user": "<<redacted>>",
  "mqtt_pass": "<<redacted>>",
  "port": 8888
}

```
I am trying to work out what exactly is unauthorised, but the logs are very limited.

Appreciate any help that can be provided.

[EDIT] Got it working by changing to 'fglair-us', then after Home Assistant saw it (in a disabled state) I changed back to 'Fglair-eu' and it worked.
