### ISSUE TITLE
No switch dry to cool

### ISSUE THREAD

**Issue by wifi75** [deiger/AirCon#184]
Hello I have two AC code: hisense-eu  if I'm on dry you can't switch to cool, why?
let's say it never worked.

**Comment by dvdavide** [comment]
Not sure why it does that from the thermostat card, but I found a workaround by adding a separate [MQTT select](https://www.home-assistant.io/integrations/select.mqtt/)

Code in configuration.yaml is like:
```
mqtt:
  select:
    - name: "Livingroom AC Work Mode"
      command_topic: "hisense_ac/xyxyxyxyxyxy/t_work_mode/command"
      state_topic: "hisense_ac/xyxyxyxyxyxy/t_work_mode/status"
      options:
        - "off"
        - "cool"
        - "heat"
        - "auto"
        - "dry"
        - "fan_only"

```
It's not completely failproof, but it fails 10% of the time instead of 90%, in my experience.

Someting similar can be also used for sleep mode:
```
  - name: "Livingroom AC Sleep Mode"
    command_topic: "hisense_ac/xyxyxyxyxyxy/t_sleep/command"
    state_topic: "hisense_ac/xyxyxyxyxyxy/t_sleep/status"
    options:
      - "stop"
      - "one"
      - "two"
      - "three"
      - "four"
      
```
