### ISSUE TITLE
adding a new device to existing ones

### ISSUE THREAD

**Issue by heindlalexander** [deiger/AirCon#225]
I have 2 devices already added using the SmartLive-App (hismart-eu)
I added a 3rd device (sadly different app), therefor added 3 lines as decribed (hisense-eu):

```
app:
  - username: myuser
    password: mypwd
    code: hisense-eu
  - username: myuser
    password: mypwd
    code: hismart-eu
log_level: INFO
mqtt_host: localhost
mqtt_user: mqtt-user
mqtt_pass: WintelTestAdmin99
port: 18830
```

addon was restarted in home assistant. even restarted the whole system.
sadly no device is added. I see no hints in the log, as if it doesn't try to contact it.
