### ISSUE TITLE
Incorrect negative temperatures with AEH-W4E1

### ISSUE THREAD

**Issue by togume** [deiger/AirCon#246]
First, thanks for this solution!!!

New install of HA, AirCon does control the ACs, but the temperature is incorrect:
<img width="388" alt="image" src="https://github.com/deiger/AirCon/assets/1534543/a2055713-09e1-41a0-a2d5-95d287365ac1">

Other ACs and devices with temperature do correctly show up in Celsius.

The LED display on the AC changes to F when controlled via HA.

The AI-Home app on iOS does show the controls in C, but interestingly enough, when controlled via HA, it shows current temperature in F.

Here is the config for the Add On:
```
log_level: INFO
mqtt_host: 192.168.86.25
mqtt_user: mqtt_user
mqtt_pass: PASS
port: 8888
app:
  - username: email
    password: PASS
    code: hismart-us
local_ip: 192.168.86.25
```

How can this be fixed?
