### ISSUE TITLE
notifier.py:121] Failed to connect to 10.0.0.26, maybe it is offline?

### ISSUE THREAD

**Issue by SK7WALKER** [deiger/AirCon#269]
all of a sudden im getting this in my log, had it working before with no issues, lately i have updated to the latest hass os version, the ip address of the aircon isnt even the 10.0.0.26 being reported in the error message, my config looks like that:
log_level: INFO
mqtt_host: core-mosquitto
mqtt_port: 1883
mqtt_user: homeassistant
mqtt_pass: xxx
port: 8321
app:
  - username: ......
    password: ......
    code: hisense-us
local_ip: 10.0.0.39 - tried removing this optional entry or replacing it with actual local ip of air conditioner to no avail 

help please :)

**Comment by tomekszy** [comment]
the same here, my config is:
```
log_level: WARNING
mqtt_host: localhost
mqtt_port: 1883
mqtt_user: mqtt-user
mqtt_pass: xxx
port: 8888
app:
  - username: xxx
    password: xxx
    code: hisense-eu
local_ip: 192.168.0.127
```
and my A/C has this address, I can connect to it by Hismart Life app on phone, also it is pingable, but in HA in AirCon addon logs I have:
```
E0828 08:53:36.397  notifier.py:121] Failed to connect to 192.168.0.25, maybe it is offline?
```
In every few seconds. Of course the address from log is completley out of anything, there is no device with such address in my network.
