### ISSUE TITLE
Can't get HA to work with the add on

### ISSUE THREAD

**Issue by Alby247** [deiger/AirCon#277]
I have had my Fujitsu working with HA for several months.  I just changed my network config to move all IoT devices, including the AC, to VLAN 30.

The AC has a new IP address, 192.168.30.58.  I have connected to it with the FGLAir android app and can control it via wifi.  But I can't get HA to work with it again.

HA server is 192.168.0.33.

Mosquitto running as HA add on

My configuration (HAOS, all latest updates):

```
log_level: INFO
mqtt_host: 192.168.0.33
mqtt_port: 1883
mqtt_user: mqtt-user
mqtt_pass: password
port: 1886
local_ip: 192.168.30.58
app:
  - username: myemail@gmail.com
    password: mypassword
    code: fglair-us
```

contents of config.json file:

{"name": "AC000W000768786", "app": "fglair-us", "model": "AP-WA3E", "sw_version": "bc 2.6.17-fgl2 06/29/20 09:03:57 ID jre/mfg/2dfbf5d", "dsn": "AC000W000768786", "temp_type": "C", "mac_address": "a0cc2b3271d6", "ip_address": "192.168.30.58", "lanip_key": "DjWQMlMlO5C8Yrk7+Tavt6ceDjwn/A==", "lanip_key_id": 57775}

Any ideas?

In the configuration, what does port: refer to?  Is this just an arbitrary prot number I assign?

And what should local ip be set to?  I have it set to the actual IP of the AC unit.
