### ISSUE TITLE
Hisense fan speed and orientation

### ISSUE THREAD

**Issue by wifi75** [deiger/AirCon#28]
@deiger ck007max
My configuration on hassio it is corrent but fan speed and otientation nont work... why?

```
### HiSense Air Conditioner STANZETTA ###
climate:
  - platform: mqtt
    name: "HiSense AC Stanzetta"
    current_temperature_topic: "hisense_stanzetta/f_temp_in/status"
    fan_mode_command_topic: "hisense_stanzetta/t_fan_speed/command"
    fan_mode_state_topic: "hisense_stanzetta/t_fan_speed/status"
    fan_modes:
      - "auto"
      - "lower"
      - "low"
      - "medium"
      - "high"
      - "higher"
    max_temp: "30"
    min_temp: "16"
    mode_command_topic: "hisense_stanzetta/t_work_mode/command"
    mode_state_topic: "hisense_stanzetta/t_work_mode/status"
    modes:
      - "fan_only"
      - "heat"
      - "cool"
      - "dry"
      - "auto"
    power_command_topic: "hisense_stanzetta/t_power/command"
    power_state_topic: "hisense_stanzetta/t_power/status"  
    precision: 1.0
    swing_mode_command_topic: "hisense_stanzetta/t_fan_power/command"
    swing_mode_state_topic: "hisense_stanzetta/t_fan_power/status"
    temperature_command_topic: "hisense_stanzetta/t_temp/command"
    temperature_state_topic: "hisense_stanzetta/t_temp/status"
    temperature_unit: "C"
    
### HiSense Air Conditioner STUDIO ###

  - platform: mqtt
    name: "HiSense AC Studio"
    current_temperature_topic: "hisense_studio/f_temp_in/status"
    fan_mode_command_topic: "hisense_studio/t_fan_speed/command"
    fan_mode_state_topic: "hisense_studio/t_fan_speed/status"
    fan_modes:
      - "auto"
      - "lower"
      - "low"
      - "medium"
      - "high"
      - "higher"
    max_temp: "30"
    min_temp: "16"  
    mode_command_topic: "hisense_studio/t_work_mode/command"
    mode_state_topic: "hisense_studio/t_work_mode/status"
    modes:
      - "fan_only"
      - "heat"
      - "cool"
      - "dry"
      - "auto"
    power_command_topic: "hisense_studio/t_power/command"
    power_state_topic: "hisense_studio/t_power/status"  
    precision: 1.0
    swing_mode_command_topic: "hisense_studio/t_fan_power/command"
    swing_mode_state_topic: "hisense_studio/t_fan_power/status"
    temperature_command_topic: "hisense_studio/t_temp/command"
    temperature_state_topic: "hisense_studio/t_temp/status"
    temperature_unit: "C"
   
switch:
  - platform: mqtt
    name: HiSense AC Stanzetta
    state_topic: "hisense_stanzetta/t_power/status"
    command_topic: "hisense_stanzetta/t_power/command"
    payload_on: "on"
    payload_off: "off"
    qos: 1   

  - platform: mqtt
    name: HiSense AC Studio
    state_topic: "hisense_studio/t_power/status"
    command_topic: "hisense_studio/t_power/command"  
    payload_on: "on"
    payload_off: "off"
    qos: 1
```   
here Iwen I set fan to High after 2 second it retutn to AUTO why?
![image](https://user-images.githubusercontent.com/31816231/86533192-937a6080-becf-11ea-98c1-d7dff88c9566.png)
