### ISSUE TITLE
docker-compose.yml volume mapping is incorrect

### ISSUE THREAD

**Issue by rotem925** [deiger/AirCon#65]
Hi @deiger
Your docker-compose.yml is incorrect.
The volume you map should reflect the config path in your environment variable.

**Comment by deiger** [comment]
Do you mean it should be
```yaml
volumes:
       - /config:/opt/hisense
```
?

**Comment by rotem925** [comment]
I mean it should be /config, just as the value of the CONFIG_DIR env. Or, you change the CONFIG_DIR to /opt/hisense

**Comment by rotem925** [comment]
Ohh, I see the confusion here, you did it the opposite way of mapping,
I would fix that to

`volumes​:
       - .​/config:/config`

**Comment by deiger** [comment]
But how should it be mapped to /opt/hisense?
The documentation is really confusing... https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference

**Comment by rotem925** [comment]
/opt/hisense holds only the config files.
I copy the files to that directory.
the Dockerfile has a default to /opt/hisense, but you overrided it in the docker-compose file.

So you have two options here
1. Change the environment in the docker-compose to `CONFIG_DIR=/opt/hisense`
2. Change the volume map to be `config:/config` (I usually do `./config:/config` ) See my comments:

See what in bold
```
version: '3'
services:
  hisense_ac:
     image: deiger/aircon:latest
     container_name: hisense_ac
     healthcheck:
       disable: true
     environment:
       - USERNAME=<app username>
       - PASSWORD=<app password>
       - APP=<app code>
       - TYPE={ac|humidifier|fgl|fgl_b}
       - LOG_LEVEL=INFO
       - MQTT_HOST=localhost
       - MQTT_USER=<mqtt username>:<mqtt password>
       - PORT=<http server port>
       - CONFIG_DIR=/config ########################
     network_mode: host
     volumes:
       - config:/opt/hisense ########################
```

**Comment by rotem925** [comment]
Attaching here what I think it should be:
```yaml

version: '3'
services:
  hisense_ac:
     image: deiger/aircon:latest
     container_name: hisense_ac
     healthcheck:
       disable: true
     environment:
       - USERNAME=<app username>
       - PASSWORD=<app password>
       - APP=<app code>
       - TYPE={ac|humidifier|fgl|fgl_b}
       - LOG_LEVEL=INFO
       - MQTT_HOST=localhost
       - MQTT_USER=<mqtt username>:<mqtt password>
       - PORT=<http server port>
       - CONFIG_DIR=/opt/hisense
     network_mode: host
     volumes:
       - ./config:/opt/hisense 
```

**Comment by deiger** [comment]
I'd like the host directory /opt/hisense to be mapped to /config internally. Setting CONFIG_DIR to the former seems odd.

**Comment by rotem925** [comment]
So you mean?:
```

version: '3'
services:
  hisense_ac:
     image: deiger/aircon:latest
     container_name: hisense_ac
     healthcheck:
       disable: true
     environment:
       - USERNAME=<app username>
       - PASSWORD=<app password>
       - APP=<app code>
       - TYPE={ac|humidifier|fgl|fgl_b}
       - LOG_LEVEL=INFO
       - MQTT_HOST=localhost
       - MQTT_USER=<mqtt username>:<mqtt password>
       - PORT=<http server port>
       - CONFIG_DIR=/config
     network_mode: host
     volumes:
       - /opt/hisense:/config 
       
```
